#pragma once

typedef enum {
    WK_BUTTON_NONE = 0,

    WK_BUTTON_MOUSE_LEFT, WK_BUTTON_MOUSE_RIGHT, WK_BUTTON_MOUSE_MIDDLE, WK_BUTTON_MOUSE_EXTRA_1, WK_BUTTON_MOUSE_EXTRA_2,

    WK_BUTTON_LEFT_ALT, WK_BUTTON_LEFT_CONTROL, WK_BUTTON_LEFT_SHIFT, WK_BUTTON_LEFT_SUPER, WK_BUTTON_PRINT_SCREEN, WK_BUTTON_RIGHT_ALT, WK_BUTTON_RIGHT_CONTROL, WK_BUTTON_RIGHT_SHIFT, WK_BUTTON_RIGHT_SUPER,

    WK_BUTTON_APOSTROPHE, WK_BUTTON_BACKSLASH, WK_BUTTON_COMMA, WK_BUTTON_EQUAL, WK_BUTTON_GRAVE_ACCENT, WK_BUTTON_LEFT_BRACKET, WK_BUTTON_DASH, WK_BUTTON_PERIOD, WK_BUTTON_RIGHT_BRACKET, WK_BUTTON_SEMICOLON, WK_BUTTON_SLASH, WK_BUTTON_WORLD_2,

    WK_BUTTON_CAPS_LOCK, WK_BUTTON_NUM_LOCK, WK_BUTTON_SCROLL_LOCK, WK_BUTTON_PAUSE, WK_BUTTON_INSERT, WK_BUTTON_MENU, WK_BUTTON_ENTER, WK_BUTTON_CIRCUMFLEX,
    WK_BUTTON_BACKSPACE, WK_BUTTON_DELETE, WK_BUTTON_TAB, WK_BUTTON_TILDE, WK_BUTTON_RETURN, WK_BUTTON_ESCAPE, WK_BUTTON_SPACE, WK_BUTTON_PLUS, WK_BUTTON_MINUS,
    WK_BUTTON_HOME, WK_BUTTON_END, WK_BUTTON_PAGE_UP, WK_BUTTON_PAGE_DOWN, WK_BUTTON_UP, WK_BUTTON_DOWN, WK_BUTTON_RIGHT, WK_BUTTON_LEFT,

    WK_BUTTON_A, WK_BUTTON_B, WK_BUTTON_C, WK_BUTTON_D, WK_BUTTON_E, WK_BUTTON_F, WK_BUTTON_G, WK_BUTTON_H, WK_BUTTON_I, WK_BUTTON_J, WK_BUTTON_K, WK_BUTTON_L, WK_BUTTON_M,
    WK_BUTTON_N, WK_BUTTON_O, WK_BUTTON_P, WK_BUTTON_Q, WK_BUTTON_R, WK_BUTTON_S, WK_BUTTON_T, WK_BUTTON_U, WK_BUTTON_V, WK_BUTTON_W, WK_BUTTON_X, WK_BUTTON_Y, WK_BUTTON_Z,

    WK_BUTTON_0, WK_BUTTON_1, WK_BUTTON_2, WK_BUTTON_3, WK_BUTTON_4,
    WK_BUTTON_5, WK_BUTTON_6, WK_BUTTON_7, WK_BUTTON_8, WK_BUTTON_9,

    WK_BUTTON_NUM_0, WK_BUTTON_NUM_1, WK_BUTTON_NUM_2, WK_BUTTON_NUM_3, WK_BUTTON_NUM_4,
    WK_BUTTON_NUM_5, WK_BUTTON_NUM_6, WK_BUTTON_NUM_7, WK_BUTTON_NUM_8, WK_BUTTON_NUM_9,

    WK_BUTTON_NUM_ADD, WK_BUTTON_NUM_DECIMAL, WK_BUTTON_NUM_DIVIDE, WK_BUTTON_NUM_ENTER, WK_BUTTON_NUM_MULTIPLY, WK_BUTTON_NUM_SUBTRACT,

    WK_BUTTON_F1, WK_BUTTON_F2, WK_BUTTON_F3, WK_BUTTON_F4, WK_BUTTON_F5, WK_BUTTON_F6, WK_BUTTON_F7, WK_BUTTON_F8, WK_BUTTON_F9, WK_BUTTON_F10, WK_BUTTON_F11, WK_BUTTON_F12,
    WK_BUTTON_F13, WK_BUTTON_F14, WK_BUTTON_F15, WK_BUTTON_F16, WK_BUTTON_F17, WK_BUTTON_F18, WK_BUTTON_F19, WK_BUTTON_F20, WK_BUTTON_F21, WK_BUTTON_F22, WK_BUTTON_F23, WK_BUTTON_F24,
} wk_button;

typedef enum
{
    WK_BUTTON_MOD_SHIFT = 0x001,
    WK_BUTTON_MOD_CONTROL = 0x002,
    WK_BUTTON_MOD_ALT = 0x004,
    WK_BUTTON_MOD_SUPER = 0x008
} wk_button_mod;