#version 450

// Uniform buffer for scene matrices
layout(binding = 0, set = 0) uniform SceneMatrices {
    mat4 viewProj;
} ubo;

// Vertex attributes
layout(location = 0) in vec3 inPosition;

// Instance attributes
layout(location = 1) in mat4 inInstanceMatrix;  // Takes locations 1-4
layout(location = 5) in uint inObjectID;

// Output to fragment shader
layout(location = 0) flat out uint outObjectID;

// Built-in outputs
out gl_PerVertex {
    vec4 gl_Position;
};

void main()
{
    gl_Position = ubo.viewProj * inInstanceMatrix * vec4(inPosition, 1.0);
    outObjectID = inObjectID;

    // Note: gl_PrimitiveID is automatically generated by the GPU
    // and will be available in the fragment shader
}