include(FetchContent)

set(SPIRV_CROSS_SHARED OFF CACHE BOOL "SPIRV_CROSS_SHARED")
set(SPIRV_CROSS_STATIC ON CACHE BOOL "SPIRV_CROSS_STATIC")
set(SPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS ON CACHE BOOL "SPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS")
set(SPIRV_CROSS_ENABLE_TESTS OFF CACHE BOOL "SPIRV_CROSS_ENABLE_TESTS")
set(SPIRV_CROSS_ENABLE_CPP OFF CACHE BOOL "SPIRV_CROSS_ENABLE_CPP")
set(SPIRV_CROSS_CLI OFF CACHE BOOL "SPIRV_CROSS_CLI")

if (WINDOWS)
    set(SPIRV_CROSS_ENABLE_MSL OFF CACHE BOOL "SPIRV_CROSS_ENABLE_MSL")
endif()
if (APPLE)
    set(SPIRV_CROSS_ENABLE_HLSL OFF CACHE BOOL "SPIRV_CROSS_ENABLE_HLSL")
endif()

FetchContent_Declare(
        SPIRV-Cross
        GIT_REPOSITORY https://github.com/KhronosGroup/SPIRV-Cross.git
        GIT_TAG main
        CMAKE_ARGS -DSPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS=ON -DSPIRV_CROSS_CLI=OFF -DSPIRV_CROSS_SHARED=OFF -DSPIRV_CROSS_STATIC=ON
        GIT_SHALLOW TRUE
)
FetchContent_MakeAvailable(SPIRV-Cross)